# Generated by Django 5.0.3 on 2024-03-05 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='description',
            new_name='description_generale',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='montant_recompense',
            new_name='montant_recompense_total',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='palier_actuel',
        ),
        migrations.CreateModel(
            name='Palier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('niveau', models.IntegerField()),
                ('montant_recompense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paliers', to='test_app.challenge')),
            ],
        ),
    ]
