# Generated by Django 5.0.3 on 2024-03-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_categorie_challenge_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
